public enum SYMBOL_SCIENCE { CIRCLE, COMPAS, MORTAR, SEXTAN, SPHERE, WEIGHT, FEATHER };

public enum SIGN_CIVILIAN { NONE, DROP, MASK, MOON, SUN, PILLAR, BUILDING }
public enum SIGN_MILITARY { NONE, SWORD, HELM, SHIELD, TOWER, HORSESHOE }
public enum SIGN_SCIENCE { NONE, BOOK, COG, HARP, LAMPA }
public enum SIGN_COMMERCIAL { NONE, JUG, BARREL }

public enum CARD_TYPE {MANUFACTURE, RAW_MATERIAL, CIVILIAN, SCIENTIFIC, COMMERCIAL, MILITARY, GUILD }
public enum PRODUCE {ROCK, BRICK, WOOD, GLASS, PAPYRUS, GOLD }