public enum SYMBOL_SCIENCE { CIRCLE, COMPAS, MORTAR, SEXTAN, SPHERE, WEIGHT };

public enum SIGN_SCIENCE {BOOK, COG, HARP, LAMPA}
public enum SIGN_MILITARY {SWORD, HELM, SHIELD, TOWER, HORSESHOE }
public enum SIGN_COMMERCIAL {JUG, BARREL }

public enum CARD_TYPE {MANUFACTURE, RAW_MATERIAL, CIVILIAN, SCIENTIFIC, COMMERCIAL, MILITARY, GUILD }
public enum PRODUCE {ROCK, BRICK, WOOD, GLASS, PAPYRUS }