public enum SYMBOL_SCIENCE {NONE, CIRCLE, COMPAS, MORTAR, SEXTAN, SPHERE, WEIGHT, FEATHER };

public enum SYMBOL_CARD
{
    NONE, DROP, MASK, MOON, SUN, PILLAR, BUILDING,
    SWORD, HELM, SHIELD, TOWER, HORSESHOE,
    BOOK, COG, HARP, LAMPA,
    JUG, BARREL
}

public enum CARD_TYPE {NONE, MANUFACTURE, RAW_MATERIAL, CIVILIAN, SCIENTIFIC, COMMERCIAL, MILITARY, GUILD }
public enum PRODUCE {NONE, ROCK, BRICK, WOOD, GLASS, PAPYRUS, GOLD }